import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className='bg-lime-700'>
      <Head>
        <title>IMMO-WEB</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>ceg</div>
    </div>
  );
}
