import Head from "next/head";
import Image from "next/image";
import Header from "../components/all/header";
import Hero from "../components/hero";
import Container from "../components/shared/composers/container";
import { motion } from "framer-motion";
import { useState } from "react";

export default function Home() {
  return (
    <div className='bg-[#3B3C3E] h-screen !text-white'>
      <Head>
        <title>IMMO-WEB</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Hero />

      <Header />
    </div>
  );
}
